providers:
  inference:
    - provider_id: llama
      provider_type: remote::ollama
      #config:
      # api_key: ${env.OLLAMA_API_KEY}
  safety:
    - provider_id: llama-shields
      provider_type: inline::llama-shields
  config:
    base_url: http://localhost:11434
    model: phi3.5:latest   # or your preferred model